### ISSUE TITLE
add citation 

### ISSUE THREAD

**Issue by faroit** [hplt-project/sacremoses#145]
Hi, it would be great to add a way to cite sacremoses, either via githubs [new citation file](https://citation-file-format.github.io/) or via zenodo?

**Comment by jelmervdl** [comment]
Hey @alvations (or @XapaJIaMnu @kpu) did sacremoses ever get a tool paper? A quick search through Google Scholar reveals most papers just footnote the repository.

**Comment by alvations** [comment]
It was kind of by design to not have a paper so that the tool can't be attributed to/claimed by to any company that I work(ed) for =) 

But now that it is under the the hplt project, I am okay with any citation and okay with anyone on the author list, as long as the tool remain MIT licensed (or any commercially use-able license) and always open source.

**Comment by faroit** [comment]
@alvations @jelmervdl did you come up with a path towards getting citable DOI?

**Comment by jelmervdl** [comment]
I think the best way to "cite" Sacremoses at this moment is just a footnote with a link to Github. It will be more useful than anything else to most readers. It really is just a tool, not a research project.

I don't expect there will ever be a paper dedicated to Sacremoses, and just mentioning it in an HPLT project paper and then making that the canonical citation seems less helpful than a footnote.

**Comment by faroit** [comment]
@jelmervdl Happy to cite it this way. 

Though I disagree on 

> It really is just a tool, not a research project.

This project is extremely valuable to carry out research that it deserves citations. This is what https://joss.theoj.org/ is for. Please consider submitting there.
